import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'zh' | 'en' | 'ja';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  zh: {
    home: '首页',
    alicloud: '阿里云国际站',
    aws: 'AWS亚马逊云',
    aws_ec2: 'AWS EC2优惠',
    migration: '上云迁移',
    partner: '合作代理',
    tutorials: '关于云服务器',
    home_hero_title: '全球云服务器总代理',
    home_hero_subtitle_1: '无需信用卡、免备案、隐私安全',
    home_hero_subtitle_2: '即充即用、长期稳定、高效无忧',
    home_hero_subtitle_3: '365*24H技术支持，全渠道支付',
    contact: '！',
    huawei_cloud: '华为云',
    tencent_cloud: '腾讯云',
    feature_discount_title: '优惠折扣',
    feature_discount_desc: '减了又减的折扣叠加方案',
    feature_no_filing_title: '免备案',
    feature_no_filing_desc: '只需邮箱轻松注册使用',
    feature_support_title: '技术支持',
    feature_support_desc: '迁移上云，多云管理',
    feature_payment_title: '多元支付',
    feature_payment_desc: '多币种支付',
    products_services_title: '全球云精选产品与服务',
    product_ecs: '弹性云服务器ECS',
    product_ecs_desc: '弹性、安全的虚拟云服务器',
    product_security: '云安全服务',
    product_security_desc: '解决业务所面临的外部和内部威胁',
    product_cdn: '内容分发CDN',
    product_cdn_desc: '适用于任何内容类型加速分发',
    product_oss: '对象存储OSS',
    product_oss_desc: '安全、可靠的云存储服务',
    product_rds: '云数据库RDS',
    product_rds_desc: '稳定可靠的在线数据库服务',
    product_firewall: '云防火墙',
    product_firewall_desc: '云上资产防护的统一管理',
    product_cen: '云企业网CEN',
    product_cen_desc: '提供优质、高效、稳定的云上专线',
    product_ai: 'AI大模型',
    product_ai_desc: '深度学习 科学计算 ai图形图像处理',
    buy_now: '免绑卡购买',
    purchase_process_title: '全球云购买流程',
    consult_now: '我要咨询',
    step_1_title: '咨询产品报价',
    step_1_desc: '在线咨询或电话联系，获取产品报价',
    step_2_title: '注册云账号',
    step_2_desc: '客服将协助您注册国际官网会员',
    step_3_title: '关联成为VIP客户',
    step_3_desc: '注册完成后，自动关联成为VIP客户',
    step_4_title: '通过我们充值余额',
    step_4_desc: '充值到账仅需1分钟，费用中心可看余额',
    step_5_title: '官网下单',
    step_5_desc: '客户自己官网下单购买服务器等产品',
    step_6_title: '发票 / 收据索取',
    step_6_desc: '充值成功后可向我们索取发票、收据',
    payment_methods_title: '支持多种货币支付方式',
    alipay: '支付宝',
    wechat_pay: '微信支付',
    bank_transfer: '银行转账',
    union_pay: '银联支付',
    professional_solutions_title: '整个全球公有云，打造专业解决方案',
    solution_ecommerce: '跨境电商解决方案',
    solution_ecommerce_desc: '通过利用优质全球云资源，帮助不同类型的海外电商用户实现业务的快速落地',
    solution_overseas: '海外运营账号',
    solution_overseas_desc: '提供独享IP资源，有效免除账号关联风险',
    solution_migration: '多云数据迁移服务',
    solution_migration_desc: '提供AWS高效迁移服务，充分降本增效',
    solution_gaming: '海外游戏上云解决方案',
    solution_gaming_desc: '针对游戏类业务，提供全球服加速和安全类产品',
    customized_solutions_title: '定制化解决方案',
    industry_gaming: '游戏平台',
    industry_gaming_desc: '为游戏行业打造全面、高质量的云服务平台',
    industry_fintech: '金融科技',
    industry_fintech_desc: '云基础设施允许金融科技公司快速创新',
    industry_live: '直播大平台',
    industry_live_desc: '提供直播、移动直播SDK、点播、短视频SDK等一站式解决方案',
    industry_ecommerce: '电商解决方案',
    industry_ecommerce_desc: '为电商平台提供稳定可靠的云服务支持',
    aws_infrastructure_title: 'AWS全球基础设施地图',
    aws_infrastructure_desc: 'AWS云现已在全球25个地理区域内运营着81个可用区，服务245个国家和区域',
    aws_infrastructure_regions: '包括北美、南美、欧洲、中国、亚太地区、南非和中东地区',
    learn_more: '了解更多',
    site_name: 'ProductHub',
    all_rights_reserved: '版权所有',
  },
  en: {
    home: 'Home',
    alicloud: 'Alibaba Cloud',
    aws: 'AWS Cloud',
    aws_ec2: 'AWS EC2 Offers',
    migration: 'Cloud Migration',
    partner: 'Partner Program',
    tutorials: 'Cloud Server Tutorials',
    home_hero_title: 'Global Cloud Server Agent',
    home_hero_subtitle_1: 'No Credit Card, No Filing, Privacy Protected',
    home_hero_subtitle_2: 'Instant Recharge, Long-term Stability',
    home_hero_subtitle_3: '365*24H Technical Support',
    contact: ' Contact',
    huawei_cloud: 'Huawei Cloud',
    tencent_cloud: 'Tencent Cloud',
    feature_discount_title: 'Special Discounts',
    feature_discount_desc: 'Stackable discount plans',
    feature_no_filing_title: 'No Filing Required',
    feature_no_filing_desc: 'Easy registration with email',
    feature_support_title: 'Technical Support',
    feature_support_desc: 'Cloud migration, multi-cloud management',
    feature_payment_title: 'Multiple Payment',
    feature_payment_desc: 'Multi-currency payment',
    products_services_title: 'Global Cloud Featured Products',
    product_ecs: 'Elastic Cloud Server ECS',
    product_ecs_desc: 'Elastic and secure virtual cloud server',
    product_security: 'Cloud Security Service',
    product_security_desc: 'Address business threats',
    product_cdn: 'Content Delivery Network',
    product_cdn_desc: 'Accelerate content distribution',
    product_oss: 'Object Storage Service',
    product_oss_desc: 'Secure cloud storage',
    product_rds: 'Cloud Database RDS',
    product_rds_desc: 'Reliable database service',
    product_firewall: 'Cloud Firewall',
    product_firewall_desc: 'Unified asset protection',
    product_cen: 'Cloud Enterprise Network',
    product_cen_desc: 'Stable cloud private line',
    product_ai: 'AI Large Model',
    product_ai_desc: 'Deep learning and AI processing',
    buy_now: 'Buy Now',
    purchase_process_title: 'Purchase Process',
    consult_now: 'Consult Now',
    step_1_title: 'Product Quote Inquiry',
    step_1_desc: 'Online consultation for quotes',
    step_2_title: 'Register Cloud Account',
    step_2_desc: 'Customer service assists registration',
    step_3_title: 'Become VIP Customer',
    step_3_desc: 'Automatic VIP status',
    step_4_title: 'Recharge Balance',
    step_4_desc: 'Instant recharge in 1 minute',
    step_5_title: 'Place Order',
    step_5_desc: 'Order on official website',
    step_6_title: 'Invoice / Receipt',
    step_6_desc: 'Request invoice after recharge',
    payment_methods_title: 'Multiple Payment Methods',
    alipay: 'Alipay',
    wechat_pay: 'WeChat Pay',
    bank_transfer: 'Bank Transfer',
    union_pay: 'UnionPay',
    professional_solutions_title: 'Professional Solutions',
    solution_ecommerce: 'E-commerce Solution',
    solution_ecommerce_desc: 'Global cloud resources for e-commerce',
    solution_overseas: 'Overseas Account Operations',
    solution_overseas_desc: 'Dedicated IP resources',
    solution_migration: 'Data Migration Service',
    solution_migration_desc: 'Efficient AWS migration',
    solution_gaming: 'Gaming Cloud Solution',
    solution_gaming_desc: 'Comprehensive gaming solutions',
    customized_solutions_title: 'Customized Solutions',
    industry_gaming: 'Gaming Platform',
    industry_gaming_desc: 'High-quality cloud platform for gaming',
    industry_fintech: 'Financial Technology',
    industry_fintech_desc: 'Cloud infrastructure for fintech',
    industry_live: 'Live Streaming Platform',
    industry_live_desc: 'One-stop streaming solutions',
    industry_ecommerce: 'E-commerce Solution',
    industry_ecommerce_desc: 'Reliable cloud support',
    aws_infrastructure_title: 'AWS Global Infrastructure',
    aws_infrastructure_desc: 'AWS operates 81 zones in 25 regions',
    aws_infrastructure_regions: 'Including Americas, Europe, Asia Pacific, Middle East',
    learn_more: 'Learn More',
    site_name: 'ProductHub',
    all_rights_reserved: 'All Rights Reserved',
  },
  ja: {
    home: 'ホーム',
    alicloud: 'Alibaba Cloud',
    aws: 'AWSクラウド',
    aws_ec2: 'AWS EC2優待',
    migration: 'クラウド移行',
    partner: 'パートナー',
    tutorials: 'クラウドサーバーチュートリアル',
    home_hero_title: 'グローバルクラウドサーバー総代理店',
    home_hero_subtitle_1: 'クレジットカード不要、登録不要',
    home_hero_subtitle_2: '即時チャージ、長期安定',
    home_hero_subtitle_3: '365*24H技術サポート',
    contact: '連絡',
    huawei_cloud: 'Huawei Cloud',
    tencent_cloud: 'Tencent Cloud',
    feature_discount_title: '特別割引',
    feature_discount_desc: '重複割引プラン',
    feature_no_filing_title: '登録不要',
    feature_no_filing_desc: 'メールのみで簡単登録',
    feature_support_title: '技術サポート',
    feature_support_desc: 'クラウド移行、マルチクラウド管理',
    feature_payment_title: '多様な支払い',
    feature_payment_desc: '多通貨決済',
    products_services_title: 'グローバルクラウド厳選製品',
    product_ecs: '弾性クラウドサーバー',
    product_ecs_desc: '弾性的で安全なクラウドサーバー',
    product_security: 'セキュリティサービス',
    product_security_desc: 'ビジネス脅威を解決',
    product_cdn: 'コンテンツ配信',
    product_cdn_desc: 'コンテンツ配信を加速',
    product_oss: 'オブジェクトストレージ',
    product_oss_desc: '安全なクラウドストレージ',
    product_rds: 'クラウドデータベース',
    product_rds_desc: '信頼性の高いデータベース',
    product_firewall: 'ファイアウォール',
    product_firewall_desc: '統合資産保護',
    product_cen: 'エンタープライズネットワーク',
    product_cen_desc: '安定したクラウド専用線',
    product_ai: 'AI大規模モデル',
    product_ai_desc: 'ディープラーニングとAI処理',
    buy_now: '今すぐ購入',
    purchase_process_title: '購入プロセス',
    consult_now: '今すぐ相談',
    step_1_title: '見積もり問い合わせ',
    step_1_desc: 'オンライン相談で見積もり',
    step_2_title: 'アカウント登録',
    step_2_desc: 'カスタマーサービスがサポート',
    step_3_title: 'VIP顧客になる',
    step_3_desc: '自動的にVIP顧客',
    step_4_title: '残高チャージ',
    step_4_desc: '1分で到着',
    step_5_title: '注文',
    step_5_desc: '公式サイトで注文',
    step_6_title: '請求書',
    step_6_desc: 'チャージ後に請求書を要求',
    payment_methods_title: '複数決済方法',
    alipay: 'Alipay',
    wechat_pay: 'WeChat Pay',
    bank_transfer: '銀行振込',
    union_pay: 'UnionPay',
    professional_solutions_title: '専門ソリューション',
    solution_ecommerce: 'ECソリューション',
    solution_ecommerce_desc: 'ECのためのグローバルクラウド',
    solution_overseas: '海外アカウント運営',
    solution_overseas_desc: '専用IPリソース',
    solution_migration: 'データ移行サービス',
    solution_migration_desc: '効率的なAWS移行',
    solution_gaming: 'ゲームクラウド',
    solution_gaming_desc: '包括的なゲームソリューション',
    customized_solutions_title: 'カスタマイズソリューション',
    industry_gaming: 'ゲームプラットフォーム',
    industry_gaming_desc: '高品質なクラウドプラットフォーム',
    industry_fintech: '金融テクノロジー',
    industry_fintech_desc: 'フィンテック向けインフラ',
    industry_live: 'ライブストリーミング',
    industry_live_desc: 'ワンストップソリューション',
    industry_ecommerce: 'ECソリューション',
    industry_ecommerce_desc: '信頼性の高いクラウドサポート',
    aws_infrastructure_title: 'AWSグローバルインフラ',
    aws_infrastructure_desc: 'AWS は25リージョンで81ゾーンを運用',
    aws_infrastructure_regions: '南北米、ヨーロッパ、アジア太平洋、中東を含む',
    learn_more: '詳細を見る',
    site_name: 'ProductHub',
    all_rights_reserved: '全著作権所有',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('zh');

  useEffect(() => {
    const browserLang = navigator.language.toLowerCase();
    if (browserLang.startsWith('zh')) {
      setLanguage('zh');
    } else if (browserLang.startsWith('ja')) {
      setLanguage('ja');
    } else {
      setLanguage('en');
    }
  }, []);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
